#!/bin/sh
#!/bin/sh

# # Crea el hook pre-commit
# npx husky install

# Configura el hook pre-commit

# 

# Haz que el hook pre-commit sea ejecutable
chmod +x .husky/pre-commit

# Comprobar que el mensaje de commit contiene la frase "A corregir por: ..."
current_branch=$(git symbolic-ref --short HEAD)

if [[ "$current_branch" == "hotfix/mejorasV_1_0" ]]; then
    # commit_msg_file="$1"
    # commit_msg=$(cat "$commit_msg_file")

    echo "grep" 
    for file in $(git diff --cached --name-only); do
        if  grep -q "A corregir por:"; then
        echo "El mensaje de commit debe contener la frase 'A corregir por: ...'"
        echo "Abortando el commit."
        exit 1
        fi
    done
fi