#!/bin/sh

# Comprobar que el mensaje de commit contiene la frase "A corregir por: ..."
current_branch=$(git symbolic-ref --short HEAD)

if [[ "$current_branch" == "hotfix/mejorasV_1_0" ]]; then
    commit_msg_file="$1"
    commit_msg=$(cat "$commit_msg_file")

    if [[ ! $commit_msg | grep -q "A corregir por: "* ]]; then
    echo "El mensaje de commit debe contener la frase 'A corregir por: ...'"
    echo "Abortando el commit."
    exit 1
    fi
fi